using System.Windows.Forms;

namespace CaroProjectNhom15.Forms.Auth
{
    public partial class LoginForm : Form
    {
        public LoginForm()
        {
            InitializeComponent();
        }

        /// <summary>
        /// This method is usually auto-generated by the Windows Forms designer.
        /// If missing, add a minimal stub to resolve CS0103.
        /// </summary>
       
    }
}
